### ISSUE TITLE
Errors when trying to download any video from RedBull

### ISSUE THREAD

**Issue by thisisgregm** [bboymega/rbtv-dl#4]
The script used to work for me last year.
I tried to download something recently and got always the same errors:

```
$ python3 rbtv-dl.py https://www.redbull.com/gb-en/videos/any-video-from-red-bull-website
Traceback (most recent call last):
  File "/home/username/rbtv-dl.py", line 100, in <module>
    response=json.load(StringIO(getvideo_return.text))
  File "/usr/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Any help please?

Many thanks

**Comment by thisisgregm** [comment]
Changed redbull.tv to redbull.com (lines 12-13) and now I get the error as below:
```
Traceback (most recent call last):
  File "/home/user/rbtv-dl.py", line 59, in <module>
    token=response["token"]
KeyError: 'token'
```

**Comment by sierraworks** [comment]
Here is what I figured out.
1:  undo your change
2:  go to the video in a browser and look at the source.  Find the graphql url:  like:  /v3/api/graphql/v1/v3/feed/en-US>en-INT?filter[type]=films&filter[uriSlug]=

Notice how the locale is en-INT and not en-US so I set locale = "en-INT" right before the setting of the get_video_url.


locale = "en-INT"

get_video_url="https://www.redbull.com/v3/api/graphql/v1/v3/query/"+locale+"%3E"+locale+"?filter[type]="+type+"&page[limit]=1&filter[uriSlug]="+title_url+"&rb3Schema=v1:hero"

it would probably be good to add a command line option for locale.

**Comment by thisisgregm** [comment]
OK will try it. Thanks. I wrote own bash script doing that (based on line 118 of rbtv-dl.py), but need to find the playlist link manually.
Also realized recently that yt-dlp (https://github.com/yt-dlp/yt-dlp) supports RebBull too, so I've been using that.

**Comment by bboymega** [comment]
A new version has been released.
